name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/deployment.yml
