name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리에서 코드 가져오기
      - uses: actions/checkout@v3

      # 2. Python 의존성 설치 및 테스트 실행
      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest
          pytest

      # 3. Kubernetes 배포
      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          kubectl apply -f ./k8s/deployment.yml
          kubectl get pods
